name: builder-docker-image-build

on: 
  push: 

  release:
    types: [created]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }} 
      - name: add sshkey
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}
      - name: builder
        env:
          ssh_deploy_key: ukHo+YrG6xulVlk3WuZd9ITOlbUiCKEApWZdy0pHkSb5QvOh4k92aPkQfNYec3Kvy878FaRY4jog2EzYCOfnuuGPilKlywgsEAajr5Ox3wj082D2plRsDVW3UjaHaeUxQjJw5yRPfjd1k3MFJfLrVMS2J8Uf0DzCFlnjAdm77AF+MrQN1HP2XdzWb3AkPqHAE/IgxdJqVf6dlgSerl1cAHhqeLvA2gR4HJPPmPc5OYEH+QCMOmNJ2zONjKd5W3mnZlQwnVJ2AcfT7L7w68uqvS/IulPhWXjFy6VSOYi7HJRxezPzf7thL5W/0z8oCcUPvTgbePNAq+g7N3nP6QGDwdYsTzrWoRTwkcpPkB9biWOwXv+TgAD3PyptWUX9XfgAYfsN4iUBKYqSTiNMsknEdo1YAQCxQomZdELkBfrjxYzXXfeoqv44c2fUUBLso5siDhs+9R1k76JeHFpOObUmwlGBHf/TM9LUhaHTdSSIoscxo44VmHSkx06kUwxvKJVNzRQPJdJQK6phLKf4W4bwiRlX+6mh2Y/El2uTfqv2fNmLVvTpQOa0e5BqO4WpONxWVBIerl//Ccxk3SEdfCbxeLQaDwFeMf0k7NvxF6HNslao0Mp9TutIvYaDWtig+TaVO4X5bA4pNCno0i9EwWcs3MNHFtspCdol3GuSHbM6HO8=
          GITHUB_KEY: GBG1xY1vpnL5Popsq/qNGlFsRdnOut5eEMGM1LgPj2aneOf1ioocbizMjYhzQEMVLqYE0w7gm/DZZogZZ442sKSdRWraCGpwcZt+Xf61WbdzRDGQbTbV8oNlNlsJA51+iM/kY5uHjPkBNJIrZLEcxwEyUCgLKWM0FN1cijgG3NMEwVStoXH+2csOtyENG5bWBe0zZzhA9zK/0FxO/vv1OFjE0ICW1iITmRlMJ1zi/GT9g8hGydCM3DZV3Tr9vOFD2K7QodnlJgujm2PNG9bmDLDGI7AWO49hml5wx8zPQoqMqcWszd+2sgIjSxv18LRzNMnJ6b2tK6l0TohxlmNI1fbfiQih/NomuxjG991Z6ypXCURPWp5n8lqyHYrZ2JGqSd30cxqJGZw7lV65YIl7IMRTNnjEWYrXCz2B5UpZGQ2oFWw80hnQb7xe2jEaWfD9wgEYfIvsMU8L/MpTQE8eC7B/ioU4BQ8GvLoDcolXQEcvJ4YsPXlpPsrYPkZBhE+CGCzUuLY80m1YGU7OQhkrk57wyaMuV5vu5ZFYdGHUTAo2aGqg45XFJjhSgAm/VnS4jv10gK/ZGUzO0+cpzN3jhLkeK3U5JXiYc2+mC/32rtb30gDOYsV64/2nRlXPVuyA1UBDX6M2BDq6MrkRPFFMMmyoMsnqaPGFMNc9Iu0e4lk=
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/builder"
          sudo apt install qemu-user-static g++-arm-linux-gnueabihf kpartx aria2 tree s3fs apache2
          sudo pip install requests
          ps -aux
          echo $USERNAME
          mkdir images && sudo APIKEY=${{ secrets.APIKEY }} USERNAME=${{ secrets.USERNAME }} PATH=./node_modules/.bin:$PATH ./builder --noninteractive  
          # . .travis/environment.sh
          # .travis/compress.sh
          # find / -name "treehouse*"
          # ./.travis/upload.sh
          echo 0
          sudo systemctl start apache2
          sudo curl http://localhost
          sudo systemctl stop apache2
          echo 1
          echo "${{ secrets.ACCESS_KEY_ID }}:${{ secrets.SECRET_ACCESS_KEY }}" > .passwd-s3fs
          chmod 600 .passwd-s3fs
          sudo ls -la /var/www/html
          echo 2
          sudo rm -rf /var/www/html
          sudo mkdir -p /var/www/html
          sudo chmod 666 /var/www/html
          echo 3
          sudo s3fs treehouses /var/www/html -o passwd_file=./.passwd-s3fs -o allow_other
          sudo ls -la /var/www/html
          sudo mv /var/www/html/index.html /var/www/html/index.html.old 
          echo 4
          sudo sync 
          sudo systemctl start apache2
          sudo systemctl status apache2
          sudo cat /etc/apache2/apache2.conf
          echo 5
          sudo ls -la /etc/apache2/sites-enabled
          sudo cat /etc/apache2/sites-enabled/000-default.conf
          echo 6
          sudo curl http://localhost
          echo 7
          # sudo wget -P var/www/html http://localhost/index.html
          echo 8
          sudo sync 
          sudo cat /var/www/html/index.html 
          echo 9
          sudo mv /var/www/html/index.html.new /var/www/html/index.html 