name: builder-docker-image-build

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  builder-docker-image-build:
    runs-on: ubuntu-latest
    env:
      #APIKEY: ${{ secrets.APIKEY }}
      USERNAME: rjpadilla
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }} 
      - name: builder
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/builder"
          sudo apt install qemu-user-static g++-arm-linux-gnueabihf kpartx aria2 tree 
          sudo pip install requests
          echo $USERNAME
          mkdir images && sudo PATH=./node_modules/.bin:$PATH ./builder --noninteractive