name: builder-docker-image-build

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  builder-docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }} 
      - name: builder
<<<<<<< HEAD
=======
        with:
          APIKEY: ${{ secrets.APIKEY }}
          USERNAME: ${{ secrets.USERNAME }}
>>>>>>> d3d700030bbf2b70ae9844096d034a9c0b93791e
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export ACTIONS_RUNNER_DEBUG=true
          repo="rjpadilla/builder"
          sudo apt install qemu-user-static g++-arm-linux-gnueabihf kpartx aria2 tree 
          sudo pip install requests
          env
          echo $USERNAME
          mkdir images && sudo PATH=./node_modules/.bin:$PATH ./builder --noninteractive  